name: pr-add-label

on:
    pull_request_target:
        types: [opened, edited, reopened, synchronize]

jobs:
    add-label:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Check PR number
              id: pr_number
              run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

            - name: Run add-label Action
              uses: thinkasany/pr-label-action@master
              with:
                  github_token: ${{ secrets.ACTION_TOKEN }}
                  pr_number: ${{ env.PR_NUMBER }}
                  organize_name: EternalHeartTeam
                  team_name: eternalheartteam
