name: Create Cli Release

on:
    push:
        tags:
            - 'cli-v*'

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.repository == 'EternalHeartTeam/leetcode-practice'
        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm install
            - run: npm run build-cli
            - run: npm run publish-cli
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
